repos:
  - repo: https://github.com/PyCQA/isort
    rev: "5.13.2"
    hooks:
      - id: isort
        exclude: "__init__\\.py"
  - repo: https://github.com/psf/black
    rev: "24.4.2"
    hooks:
      - id: black
        language_version: python3
        args: ['--config=pyproject.toml']
  - repo: https://github.com/PyCQA/flake8
    rev: "7.1.0"
    hooks:
      - id: flake8
        exclude: /tests/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.11.0"
    hooks:
      - id: mypy
        additional_dependencies: [types-PyYAML==6.0.12]